### ISSUE TITLE
smart_listing.paginate broke with Ruby 3.1.1

### ISSUE THREAD

**Issue by xungngo** [Sology/smart_listing#211]
<%= smart_listing.paginate %>
Resulted `in wrong number of arguments (given 2, expected 1)`

TRACE:
[kaminari-core (1.2.2) lib/kaminari/helpers/helper_methods.rb:116:in `paginate']

[smart_listing (1.2.3) app/helpers/smart_listing/helper.rb:49:in `paginate']

**Comment by dannyvanhoof** [comment]
looks like since ruby 3, a ** is needed in front of the options dictionary: 

`@template.paginate @smart_listing.collection, **{:remote => @smart_l...`

**Comment by moirazz** [comment]
any update on this issue? I'm running into the same thing

**Comment by xungngo** [comment]
What dannyvanhoof said above BUT I would abandon this kind of gems.
